services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: jtorregrosa/runpod-gradio-aio-app:latest
    container_name: gradio-aio-app
    ports:
      - "7860:7860"
      - "8888:8888"
    volumes:
      - ./src:/workspace/app
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - JUPYTER_PASSWORD=${JUPYTER_PASSWORD}
      - WORKSPACE=/workspace
      - NVIDIA_VISIBLE_DEVICES=all