---
models:
- id: "black-forest-labs/FLUX.1-dev"
  name: "FLUX.1-dev"
  type: "flux"
  description: "FLUX.1 [dev] is an open-weight, guidance-distilled model for non-commercial applications. Directly distilled from FLUX.1 [pro], FLUX.1 [dev] obtains similar quality and prompt adherence capabilities, while being more efficient than a standard model of the same size"
  overrides:
    pipeline:
      lora_scale: 1.0
      guidance_scale: 3.5
      num_inference_steps: 50
      max_sequence_length: 512
  loras:
  - id: "contrabandista_clothes"
    name: "Contrabandista Outfit"
    repo: "jtorregrosa/misc_flux_lora"
    weight_name: "contrabandistas_outfit_flux_lora_1500.safetensors"
    trigger: "[jtcontrabandista consisting of a person with traditional black vest with red and gold embroidery over a white shirt, with a red sash around the waist and dark pants with red and gold side trim.]"
    description: "This is a LoRA trained on FLUX.1-dev to generate images of contrabandistas outfit."

  - id: "watercolour"
    name: "Watercolour Style"
    repo: "SebastianBodza/Flux_Aquarell_Watercolor_v2"
    weight_name: "lora.safetensors"
    trigger: "[AQUACOLTOK]"
    description: "This is a LoRA trained on FLUX.1-dev to generate images with a watercolour style."

  - id: "ghibsky"
    name: "Ghibsky Style"
    repo: "aleksa-codes/flux-ghibsky-illustration"
    weight_name: "lora.safetensors"
    trigger: "[GHIBSKY style painting]"
    description: "The Flux Ghibsky Illustration model generates landscapes that blend serene, surreal skies with intricate, Ghibli-inspired details. This fusion of styles creates enchanting scenes that capture the essence of both Ghibli's whimsical charm and Makoto Shinkai's atmospheric beauty. Perfect for creating dreamy visuals. You can also run the model on Replicate. Feedback is welcome!"

  - id: "frostinglane"
    name: "Frosting Lane Style"
    repo: "alvdansen/frosting_lane_flux"
    weight_name: "flux_dev_frostinglane_araminta_k.safetensors"
    trigger: "[frstingln illustration]"
    description: "This is a LoRA trained on FLUX.1-dev to generate images with a frosting lane illustration style."

  - id: "simplevector"
    name: "Simple Vector Style"
    repo: "renderartist/simplevectorflux"
    weight_name: "Simple_Vector_Flux_v2_renderartist.safetensors"
    trigger: "[v3ct0r style, simple vector art, isolated on white bg]"
    description: "This is a LoRA trained on FLUX.1-dev to generate images with a frosting lane illustration style."

  - id: "coloringbook"
    name: "Coloring Book Style"
    repo: "renderartist/coloringbookflux"
    weight_name: "c0l0ringb00k_Flux_v1_renderartist.safetensors"
    trigger: "[c0l0ringb00k coloring book page]"
    description: "Coloring Book Flux is a Flux LoRA trained on a 100 image synthetic dataset that I personally generated, the images in the dataset were mostly human, vehicles and animal illustrations."

  - id: "boring-dragon/sketchy"
    name: "Sketchy Style"
    repo: "boring-dragon/sketchy"
    weight_name: "sketchy.safetensors"
    trigger: "[GETSKETCHY --s 28]"
    description: "This is a LoRA trained on FLUX.1-dev to generate images using Sketchy style."

  - id: "WizWhite/wizard-s-paper-model-universe"
    name: "Wizard's Paper Style"
    repo: "WizWhite/wizard-s-paper-model-universe"
    weight_name: "Wiz-Paper_Model_Universe.safetensors"
    trigger: "[A highly detailed paper model cutout]"
    description: "This is a LoRA trained on FLUX.1-dev to generate images using Wizard's Paper style."

  - id: "jtorregrosa/endless_flux_lora"
    name: "Endless Line Style"
    repo: "jtorregrosa/endless_flux_lora"
    weight_name: "endless_flux_lora_v1.safetensors"
    trigger: "[jtendless Lines in pure black and white background]"
    description: "This is a LoRA trained on FLUX.1-dev to generate images using an endless line style."

  - id: "jtcontrabandistas"
    name: "Old Contrabandistas Style"
    repo: "jtorregrosa/misc_flux_lora"
    weight_name: "jtcontrabandistas_flux_lora_v1.safetensors"
    trigger: "[jtcontrabandista, Romantic-era watercolor illustration depicting a contrabandista in historical clothing. The style includes soft, fluid washes with natural earthy tones, and dramatic yet subtle shading. The figure is shown in a dynamic pose, suggesting motion or storytelling, with a minimalist atmospheric background typical of early 19th-century Romanticism. The composition emphasizes character expression and cultural attire, with muted, warm color hues that evoke a sense of nostalgia]"
    description: "This is a LoRA trained on FLUX.1-dev to generate images using an Old Contrabandistas Style."

  - id: "jtorregrosa"
    name: "Myself"
    repo: "jtorregrosa/misc_flux_lora"
    weight_name: "jtorregrosa_flux_lora_v1.safetensors"
    trigger: "[jtorregrosa]"
    description: "This is a LoRA trained on FLUX.1-dev to generate images of my self."

  - id: "midomenech"
    name: "My Girlfriend"
    repo: "jtorregrosa/misc_flux_lora"
    weight_name: "midomenech_flux_lora_v1.safetensors"
    trigger: "[midomenech]"
    description: "This is a LoRA trained on FLUX.1-dev to generate images of my girlfriend."

  - id: "W4T3RC0L0UR"
    name: "W4T3RC0L0UR Style"
    repo: "jtorregrosa/misc_flux_lora"
    weight_name: "watercolour_23000_lora_weights.safetensors"
    trigger: "[W4T3RC0L0UR style]"
    description: "This is a LoRA trained on FLUX.1-dev to generate images using W4T3RC0L0UR style."
    
  - id: "Shakker-Labs/FLUX.1-dev-LoRA-One-Click-Creative-Template"
    name: "Stickers Cartoon"
    repo: "Shakker-Labs/FLUX.1-dev-LoRA-One-Click-Creative-Template"
    weight_name: "FLUX-dev-lora-One-Click-Creative-Template.safetensors"
    trigger: "[cartoon picture]"
    description: "This is a LoRA trained on FLUX.1-dev by Nvwa_model_studio for creative sticker-like photos."
    
  - id: "Shakker-Labs/FLUX.1-dev-LoRA-AntiBlur"
    name: "AntiBlur"
    weight_name: "FLUX-dev-lora-AntiBlur.safetensors"
    trigger: "Shakker-Labs/FLUX.1-dev-LoRA-AntiBlur"
    description: "This is a functional LoRA trained on FLUX.1-dev for deep DoF (Anti-Blur🔥) by Vadim_Fedenko on Shakker AI."
    
  - id: "Shakker-Labs/FLUX.1-dev-LoRA-Children-Simple-Sketch"
    name: "Children Sketch"
    repo: "Shakker-Labs/FLUX.1-dev-LoRA-Children-Simple-Sketch"
    weight_name: "FLUX-dev-lora-children-simple-sketch.safetensors"
    trigger: "[sketched style]"
    description: "This is a LoRA trained on FLUX.1-dev for Children's Simple-Sketch by Hongke on Shakker AI."
    
  - id: "Shakker-Labs/FLUX.1-dev-LoRA-MiaoKa-Yarn-World"
    name: "Yarn World"
    repo: "Shakker-Labs/FLUX.1-dev-LoRA-MiaoKa-Yarn-World"
    weight_name: "FLUX-dev-lora-MiaoKa-Yarn-World.safetensors"
    trigger: "[mkym this is made of wool]"
    description: "This is a LoRA (MiaoKa-Yarn-World) trained on FLUX.1-dev by MIAOKA for creating wool yarn art. It is capable of producing intricate and realistic woolen textures and patterns while maintaining high performance."
    
  - id: "Shakker-Labs/FLUX.1-dev-LoRA-Logo-Design"
    name: "Minimalistic Logo"
    repo: "Shakker-Labs/FLUX.1-dev-LoRA-Logo-Design"
    weight_name: "FLUX-dev-lora-Logo-Design.safetensors"
    trigger: "[wablogo, logo, Minimalist]"
    description: "This is a LoRA (Logo-Design) trained on FLUX.1-dev by CJim on Shakker AI."

  - id: "Shakker-Labs/AWPortrait-FL"
    name: "Portrait"
    repo: "Shakker-Labs/AWPortrait-FL"
    weight_name: "AWPortrait-FL-lora.safetensors"
    trigger: "[close up portrait]"
    description: "AWPortrait-FL is finetuned on FLUX.1-dev using the training set of AWPortrait-XL and nearly 2,000 fashion photography photos with extremely high aesthetic quality. It has remarkable improvements in composition and details, with more delicate and realistic skin and textual. Trained by DynamicWang at AWPlanet."

  - id: "CultriX/flux-nsfw-highress"
    name: "NSFW"
    repo: "CultriX/flux-nsfw-highress"
    weight_name: "nsfw-highress.safetensors"
    trigger: "[nsfw]"
    description: "This is a LoRA trained on FLUX.1-dev for generating NSFW nude content"

  - id: "alimama-creative/FLUX.1-Turbo-Alpha"
    name: "FLUX.1-Turbo-Alpha"
    repo: "alimama-creative/FLUX.1-Turbo-Alpha"
    weight_name: "diffusion_pytorch_model.safetensors"
    trigger: ""
    description: "This checkpoint is a 8-step distilled Lora, trained based on FLUX.1-dev model. We use a multi-head discriminator to improve the distill quality. Our model can be used for T2I, inpainting controlnet and other FLUX related models. The recommended guidance_scale=3.5 and lora_scale=1. Our Lower steps version will release later."

- id: "black-forest-labs/FLUX.1-schnell"
  name: "FLUX.1-schnell"
  type: "flux"
  description: "A high-speed variant of the FLUX.1 model by Black Forest Labs, optimized for rapid inference and efficient processing in time-sensitive applications. FLUX.1 [schnell] is openly available under an Apache2.0 license."
  overrides:
    pipeline:
      lora_scale: 1.0
      guidance_scale: 0.0
      num_inference_steps: 4
      max_sequence_length: 256

- id: "stabilityai/stable-diffusion-3.5-large"
  name: "SD-3.5-large"
  type: "sd3"
  description: "An advanced image generation model by Stability AI, based on Stable Diffusion version 3.5, offering enhanced image quality and detail with a larger architecture for more complex and nuanced outputs."
  overrides:
    pipeline:
      lora_scale: 1.0
      guidance_scale: 3.5
      num_inference_steps: 28
      max_sequence_length: 512
  loras:
  - id: "Shakker-Labs/SD3.5-LoRA-Linear-Red-Light"
    name: "Linear Red Light"
    repo: "Shakker-Labs/SD3.5-LoRA-Linear-Red-Light"
    weight_name: "SD35-lora-Linear-Red-Light.safetensors"
    trigger: "[Linear red light]"
    description: "This is a LoRA that generates images using Linear Red Light style."

- id: "stabilityai/stable-diffusion-3.5-large-turbo"
  name: "SD-3.5-large-turbo"
  type: "sd3"
  description: "A performance-optimized version of Stable Diffusion 3.5 by Stability AI, designed to generate high-quality images faster while maintaining the detail and complexity of the larger model architecture."
  overrides:
    pipeline:
      lora_scale: 1.0
      guidance_scale: 0.0
      num_inference_steps: 4
      max_sequence_length: 512

- id: "dummy"
  name: "Dummy"
  type: "dummy"
  description: "A dummy image generator capable of generating images of random colors"
  overrides:
    pipeline:
      lora_scale: 1.0
      guidance_scale: 0.0
      num_inference_steps: 4
      max_sequence_length: 512

defaults:
  settings:
    models:
      base_model: "black-forest-labs/FLUX.1-dev"
      lora: ""

    output:
      width: 1024
      height: 1024
      images_per_prompt: 1

    memory:
      model_cpu_offload: false
      sequential_cpu_offload: true
      vae_slicing: false
      vae_tiling: false

    pipeline:
      lora_scale: 1.0
      guidance_scale: 3.5
      num_inference_steps: 24
      max_sequence_length: 512